-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 20:17:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dprocdb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SCHOOL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SCHOOL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `ADDRESS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GROUP` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `SCHOOL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `SCHOOL_ID_idx` (`SCHOOL_ID` ASC) VISIBLE,
  CONSTRAINT `SCHOOL_ID`
    FOREIGN KEY (`SCHOOL_ID`)
    REFERENCES `mydb`.`SCHOOL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `DURATION` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `LOCATION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LESSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LESSON` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `CONTENT` TEXT(1500) NOT NULL,
  `COURSE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `COURE_ID_idx` (`COURSE_ID` ASC) VISIBLE,
  CONSTRAINT `COURSE_ID`
    FOREIGN KEY (`COURSE_ID`)
    REFERENCES `mydb`.`COURSE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIDEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIDEO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(255) NOT NULL,
  `LESSON_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `LESSON_ID_idx` (`LESSON_ID` ASC) VISIBLE,
  CONSTRAINT `LESSON_ID`
    FOREIGN KEY (`LESSON_ID`)
    REFERENCES `mydb`.`LESSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TEST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TEST` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  `LESSON_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `LESSON_ID_idx` (`LESSON_ID` ASC) VISIBLE,
  CONSTRAINT `LESSON_ID`
    FOREIGN KEY (`LESSON_ID`)
    REFERENCES `mydb`.`LESSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QUESTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTENT` VARCHAR(150) NOT NULL,
  `TEST_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `TEST_ID_idx` (`TEST_ID` ASC) VISIBLE,
  CONSTRAINT `TEST_ID`
    FOREIGN KEY (`TEST_ID`)
    REFERENCES `mydb`.`TEST` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANSWER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ANSWER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTENT` VARCHAR(45) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `QUESTION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `QUESTION_ID_idx` (`QUESTION_ID` ASC) VISIBLE,
  CONSTRAINT `QUESTION_ID`
    FOREIGN KEY (`QUESTION_ID`)
    REFERENCES `mydb`.`QUESTION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GROUP_COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GROUP_COURSE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COURSE_ID` INT NOT NULL,
  `GROUP_ID` INT NOT NULL,
  `START_DATE` BIGINT NOT NULL,
  `FINISHED` TINYINT NOT NULL,
  `TEACHER` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `COURSE_ID_idx` (`COURSE_ID` ASC) VISIBLE,
  INDEX `GROUP_ID_idx` (`GROUP_ID` ASC) VISIBLE,
  CONSTRAINT `COURSE_ID`
    FOREIGN KEY (`COURSE_ID`)
    REFERENCES `mydb`.`COURSE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GROUP_ID`
    FOREIGN KEY (`GROUP_ID`)
    REFERENCES `mydb`.`GROUP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PENDING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PENDING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(45) NOT NULL,
  `CONTENT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `USER_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`USER` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `CONTENT` VARCHAR(300) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `GROUP_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`GROUP` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SCHOOL_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`SCHOOL` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PENDING_ID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`PENDING` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASSIGNMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASSIGNMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STARTED_DATE` VARCHAR(45) NOT NULL,
  `DATE_DUE` VARCHAR(45) NULL,
  `DEADLINE` VARCHAR(45) NOT NULL,
  `TEACHER_ID_GIVEN_ASI` INT NOT NULL,
  `ASSIGNMENT_DETAIL_idASSIGNMENT_DETAIL` INT NOT NULL,
  `TITLE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_ASSIGNMENT_TEACHER`
    FOREIGN KEY ()
    REFERENCES `mydb`.`USER` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_COMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER_COMMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `URL_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `URL_ID_idx` (`URL_ID` ASC) VISIBLE,
  INDEX `USER_ID_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `URL_ID`
    FOREIGN KEY (`URL_ID`)
    REFERENCES `mydb`.`TOPIC` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASSESSMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASSESSMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  `SCORE` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `ASSIGNMENT_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ASSIGNMENT_ID_idx` (`ASSIGNMENT_ID` ASC) VISIBLE,
  INDEX `USER_ID_idx` (`USER_ID` ASC) VISIBLE,
  UNIQUE INDEX `TITLE_UNIQUE` (`TITLE` ASC) VISIBLE,
  CONSTRAINT `ASSIGNMENT_ID`
    FOREIGN KEY (`ASSIGNMENT_ID`)
    REFERENCES `mydb`.`ASSIGNMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TEST_RESULT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TEST_RESULT` (
  `TEST_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  `SCORE` INT NOT NULL,
  PRIMARY KEY (`TEST_ID`, `USER_ID`),
  INDEX `USER_ID_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `TEST_ID`
    FOREIGN KEY (`TEST_ID`)
    REFERENCES `mydb`.`TEST` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
